// AUTO-GENERATED by scripts/compute-guide-dates.mjs — do not edit by hand.
// Last regenerated: 2026-04-27
//
// Last-modified date (YYYY-MM-DD) for each agent guide, derived from
// `git log -1 --format=%cI` on src/data/agent-guides/<slug>.ts.
//
// Used by SeoJsonLd to emit accurate JSON-LD `dateModified` per guide,
// so Google does not see all guides "updated today" on every deploy.

export const GUIDE_MODIFIED: Readonly<Record<string, string>> = Object.freeze({
  "adopter": "2026-04-27",
  "aider": "2026-04-27",
  "box": "2026-04-27",
  "claude-code": "2026-04-27",
  "cloudflare-tunnel": "2026-04-27",
  "crewai": "2026-04-27",
  "dashboard": "2026-04-27",
  "delegator": "2026-04-27",
  "docker": "2026-04-27",
  "github-actions": "2026-04-27",
  "hermes": "2026-04-27",
  "kami": "2026-04-27",
  "kaylee": "2026-04-27",
  "n8n": "2026-04-27",
  "nginx": "2026-04-27",
  "ollama": "2026-04-27",
  "postgres": "2026-04-27",
  "qdrant": "2026-04-27",
  "redis-streams": "2026-04-27",
  "systemd": "2026-04-27",
  "ufw": "2026-04-27",
  "vercel": "2026-04-27",
});
