import {
  MessageCircle,
  Mic,
  Brain,
  Clock,
  Zap,
  Shield,
  Users,
  Star,
  Lightbulb,
  Code2,
  Rocket,
  BookOpen,
  Github,
  ExternalLink,
  Sparkles,
  Phone,
  Calendar,
  Bell,
} from "lucide-react";
import type { AgentGuideData } from "@/components/agent-guide/types";

export const kamiGuideEn: AgentGuideData = {
  slug: "kami",
  agentName: "Kami",
  agentNameHe: "Kami — WhatsApp AI Agent",
  logoImage: "/images/guide-logos/kami-logo.png",
  tagline: "A personal AI assistant that lives inside WhatsApp — it listens, speaks, and remembers your conversations",
  heroDescription: "Kami is a personal AI agent that lives inside WhatsApp — the messaging app we already use every day. Instead of opening yet another app like ChatGPT or Claude, you simply send a message to a WhatsApp number and get a reply, either in text or in voice. Under the hood, Kami is a service I built in TypeScript (the modern, type-checked version of JavaScript) that runs 24/7 on a small private server. It connects to WhatsApp through Green API — a lightweight, secure gateway that shuttles messages between WhatsApp and my code. When a message arrives, it is processed by [Claude Sonnet](/en/claude-code) — one of the most capable large language models (LLMs, AI systems trained to understand and generate text) on the market today. If the message is a voice note, OpenAI Whisper transcribes it into precise Hebrew; when Kami replies, it can answer with a spoken voice generated by Google Gemini TTS (free and natural sounding). Kami's signature ability is memory: it remembers older conversations using a specialized database ([Qdrant](/en/guide/qdrant), explained in its own guide), so you can pick up on an idea you started a week ago and continue from exactly where you left off. For me (Elad), Kami has become something like a chief of staff: it sends a morning briefing, reminds me of tasks, and handles my voice messages while I'm on the road. For you, the exact same architecture can power smart 24/7 customer support, a personal tutor that walks a student through their work, a digital family companion, or any other use case you can imagine for a conversational agent that lives inside WhatsApp.",
  badgeText: "2026 · Hebrew-native WhatsApp agent · Practical guide",
  canonical: "https://fullstack-eladjak.co.il/en/guide/kami",
  heroBgImage: "/images/guides/guide-kami-hero.jpg",
  stats: [
    { label: "Availability", value: "24/7" },
    { label: "Default language", value: "Hebrew" },
    { label: "Voice transcription", value: "~2s" },
    { label: "Semantic memory", value: "1000+" },
  ],
  paradigmTitle: "Why this changes the way we work with AI",
  paradigmSub:
    "Kami is not just ChatGPT with a WhatsApp skin. It is an agent that acts on its own, preserves context across weeks, and performs real-world tasks.",
  paradigmShifts: [
    {
      before: "Open an app, type a question, wait, read the answer",
      after: "Record a voice note on your way to the car — and get a voice reply while you drive",
      icon: Mic,
    },
    {
      before: "Forget what we talked about a week ago",
      after: "Kami remembers 1000+ previous messages and connects related topics",
      icon: Brain,
    },
    {
      before: "Having to nudge yourself to start a conversation",
      after: "Kami reaches out first — morning briefings, reminders, proactive suggestions",
      icon: Sparkles,
    },
    {
      before: "Bots that answer once and then forget you exist",
      after: "Consistent personality, genuine rapport, always available like a close friend",
      icon: Users,
    },
  ],
  whoIsThisFor: [
    {
      title: "Solo founders",
      description:
        "Fast communication on the move. Capture an idea while walking and watch it turn into a task.",
      icon: Rocket,
      color: "from-emerald-500 to-teal-500",
    },
    {
      title: "Busy family managers",
      description:
        "Smart reminders, scheduling, weekly wrap-ups of what happened. Like a personal secretary.",
      icon: Calendar,
      color: "from-amber-500 to-orange-500",
    },
    {
      title: "Developers who want their own",
      description:
        "Fully open source. TypeScript, Bun, Claude API. Spin up your own version in minutes.",
      icon: Code2,
      color: "from-violet-500 to-purple-500",
    },
    {
      title: "Anyone tired of ChatGPT",
      description:
        "Kami remembers you, holds context, and speaks back in a natural human voice.",
      icon: MessageCircle,
      color: "from-pink-500 to-rose-500",
    },
  ],
  toc: [
    { id: "what-is", label: "What it is" },
    { id: "setup", label: "Setup" },
    { id: "voice", label: "Voice" },
    { id: "memory", label: "Memory" },
    { id: "proactive", label: "Proactivity" },
    { id: "bridge", label: "Agent bridge" },
    { id: "advanced", label: "Advanced" },
  ],
  sections: [
    {
      id: "what-is",
      icon: MessageCircle,
      title: "What exactly is Kami?",
      subtitle: "Your personal WhatsApp agent — with real depth",
      description:
        "Kami is a personal AI agent built by Elad — a small service written in TypeScript (the modern, type-checked flavor of JavaScript), running 24/7 on a private server (a VPS — Virtual Private Server, essentially a computer rented on the internet), and connected to WhatsApp through a gateway called Green API. When a WhatsApp message arrives, Kami forwards it to [Claude Sonnet](/en/claude-code) (one of today's most capable LLMs), which understands it and produces a reply — which flows right back to you on WhatsApp, as text or as voice.",
      color: "from-emerald-600 to-teal-500",
      difficulty: "beginner",
      beginner:
        "Think of Kami as a friend who has all the knowledge of ChatGPT, but belongs to you alone, lives inside WhatsApp, and actually remembers what you told him yesterday and last week. You type a message or record a quick voice note on your way to work, and he answers — just like a friend who is always available. The real magic is that there is no extra app to open: he lives inside the app that is already open on your phone all day.",
      content: [
        "A service running on a VPS 24/7 that listens to WhatsApp via a Green API webhook (a webhook is a 'doorbell' — an incoming call from an external server whenever something happens, in our case a new message)",
        "Every incoming message passes through [Claude Sonnet](/en/claude-code) 4.5 with a custom system prompt (the system prompt is the background instructions that tell the model who it is and how to behave — in my setup it is defined as Elad's personal assistant)",
        "Voice notes are transcribed automatically by OpenAI Whisper — a top-tier STT (Speech-to-Text, turning spoken audio into written text) service that performs excellently in Hebrew",
        "Replies go out as text or as voice through Gemini TTS (Text-to-Speech, turning text back into spoken audio) using the Charon voice — a clear, natural male voice that Google offers for free",
        "Long-term memory is stored in [Qdrant](/en/guide/qdrant) — a semantic database that lets you retrieve past messages by meaning rather than by exact keywords",
      ],
      tips: [
        "Kami is open source — the code is on GitHub, so feel free to fork it and build your own version with a completely different personality",
        "The system prompt is the heart of the personality. In system-prompt.ts you can change the tone, the role, and the instructions — for example to turn it into a legal assistant, a personal trainer, or a study buddy",
      ],
    },
    {
      id: "setup",
      icon: Zap,
      title: "Set it up in 15 minutes",
      subtitle: "What you need and how to get started",
      description:
        "Setting up Kami is a one-time process that takes about fifteen minutes for anyone with a technical background. You only need three things: a Green API account (free up to 1,000 messages a month), a [Claude](/en/claude-code) API key from Anthropic, and a small, inexpensive VPS (a virtual server rented on the internet, such as Hetzner for €5 a month). Once it is running — it just works, with no ongoing maintenance.",
      color: "from-amber-600 to-orange-500",
      difficulty: "intermediate",
      beginner:
        "If you are not a developer — this step does require someone who knows how to code, but only the first time. After the initial setup Kami runs completely on its own. You can start by experimenting with ChatGPT's memory feature for free, and move to Kami when you want something more complete that lives inside WhatsApp.",
      content: [
        "git clone https://github.com/eladjak/elad-personal-agent — download the source repository to your machine (git is a version control system that tracks changes to files)",
        "bun install — install every library Kami depends on (Bun is a modern, blazing-fast JavaScript/TypeScript runtime, an alternative to Node.js)",
        "Create a .env file with the credentials: GREEN_API_TOKEN (for WhatsApp), ANTHROPIC_API_KEY (for [Claude](/en/claude-code)), OPENAI_API_KEY (for voice transcription), GEMINI_API_KEY (for speech synthesis and memory embeddings)",
        "Connect a WhatsApp number to the Green API account — a one-time QR code scan through their dashboard, exactly like pairing WhatsApp Web",
        "Deploy to a small VPS (a €5/month Hetzner box is more than enough) and configure it as a systemd service — a Linux service manager that makes sure the process restarts automatically after a reboot and runs in the background",
        "bun build src/index.ts --outdir dist — produce a compact production bundle of roughly 1.3 MB that loads in well under a second",
      ],
      tips: [
        "Do not host Kami on AWS or GCP — WhatsApp blocks IP ranges from the big cloud providers; Hetzner, Contabo, and DigitalOcean work beautifully and cost less",
        "Green API is a cleaner gateway than alternatives such as WAHA or Puppeteer (browser automation) — the cost is pennies even if you send hundreds of messages per day",
      ],
      codeExample: {
        label: "First run",
        code: "git clone https://github.com/eladjak/elad-personal-agent.git\ncd elad-personal-agent\nbun install\ncp .env.example .env\n# Edit .env with your keys\nbun run build\nbun run start",
      },
    },
    {
      id: "voice",
      icon: Mic,
      title: "Voice: hearing and speaking",
      subtitle: "Whisper transcription → Claude → Gemini TTS",
      description:
        "This is the feature that has already become the number-one reason people adopt Kami — being able to talk to it out loud throughout the day. You record a regular WhatsApp voice note (just like you would to any friend), Kami listens, understands, and replies back in voice — which turns it into a real assistant for moments when you are driving, walking, or have your hands full.",
      color: "from-purple-600 to-violet-500",
      difficulty: "intermediate",
      beginner:
        "When you record a voice note for Kami, it sends the audio to OpenAI Whisper — an STT (Speech-to-Text, spoken audio to written text) service that works exceptionally well in Hebrew. The transcribed text is passed to [Claude](/en/claude-code), which thinks it through and writes a response. The reply goes to Gemini TTS (Text-to-Speech, written text to spoken audio), which produces a Hebrew audio file, and that file is sent back to you on WhatsApp — the whole round trip takes roughly 4 to 5 seconds.",
      content: [
        "Incoming voice note → Green API delivers a URL to the .oga file (WhatsApp's native audio format)",
        "Kami downloads the file → sends it to OpenAI Whisper with the language set to Hebrew (model=whisper-1, language=he)",
        "Within 2 to 3 seconds the transcribed text comes back — precise Hebrew, including punctuation and proper diacritics",
        "[Claude Sonnet](/en/claude-code) receives the text along with the conversation context, drafts a Hebrew reply, and hands it to Gemini TTS",
        "Gemini TTS (configured with voice=Charon, a clear male voice) returns an MP3 file → Kami uploads it back to WhatsApp",
        "The magic: if you sent text you get text back, if you sent voice you get voice back — Kami mirrors the channel you reached out on",
      ],
      tips: [
        "Whisper large-v3 is more accurate than whisper-1 in Hebrew but more expensive; for everyday conversation, whisper-1 produces excellent results at negligible cost",
        "Gemini TTS is free in most cases (within the free tier of Gemini Flash 2.5) — that saves roughly $5/month you would otherwise pay to ElevenLabs",
        "If there is heavy background noise, Groq Whisper Turbo delivers better results with blazing-fast response times — around 500 milliseconds",
      ],
    },
    {
      id: "memory",
      icon: Brain,
      title: "Semantic memory with Qdrant",
      subtitle: "Not just the last message — the last 1,000, retrieved by meaning",
      description:
        "Kami's memory lives inside [Qdrant](/en/guide/qdrant) — a vector database (a specialized store that retrieves information by meaning rather than exact keywords). Every message you send Kami, and every reply it produces, is converted into an embedding (a numeric 'fingerprint' that captures meaning — a sequence of 768 numbers in our case) and stored for future retrieval.",
      color: "from-blue-600 to-indigo-500",
      difficulty: "advanced",
      beginner:
        "The mechanism sounds complex, but the idea is simple: Kami does not remember things word for word, it remembers the concept. If you ask 'what did we say about the new diet?', it will find every relevant conversation about dieting, even if the original wording was 'healthy nutrition' or 'low-calorie meals'. That is what gives the feeling that it actually knows you, rather than just reacting to your latest message.",
      content: [
        "Every message (yours and Kami's) is stored in a collection named kami_memory inside [Qdrant](/en/guide/qdrant)",
        "The embedding is generated with gemini-embedding-001 (Google's free 768-dimensional model) — excellent in Hebrew, and no billing attached",
        "Before Kami answers, it runs a semantic search: 'what has the user asked in the past that is similar in meaning to the question right now?'",
        "It pulls the 5 to 10 most relevant past messages and slots them into the system prompt — that is how [Claude](/en/claude-code) sees the broader context",
        "The result: a feeling that Kami actually remembers you, because it actually does — the memory is anchored in meaning, not in the last words typed",
      ],
      tips: [
        "After a few months of use you build up a personal library of ideas and insights — you can export it to Markdown and treat it as a private knowledge archive",
        "[Qdrant](/en/guide/qdrant) runs for free in a [Docker](/en/guide/docker) container on the same VPS — no external cloud service or additional bill required",
      ],
      codeExample: {
        label: "Semantic memory search",
        code: "// Inside Kami's response flow\nconst memories = await qdrant.search('kami_memory', {\n  vector: embeddingOfQuestion,\n  limit: 10,\n  with_payload: true,\n});\n// The most relevant memories get added to Claude's context",
      },
    },
    {
      id: "proactive",
      icon: Sparkles,
      title: "Proactive — not just reactive",
      subtitle: "Morning briefings, end-of-day summaries, idea tracking",
      description:
        "Kami is not just another bot that waits for you to reach out — it runs cron jobs (scheduled tasks that fire automatically at fixed times, like an alarm clock for the system) that let it start conversations whenever it makes sense. That turns it from a reactive tool into a personal assistant that knows when to get in touch — very much like a secretary who reminds you about your next meeting.",
      color: "from-pink-600 to-rose-500",
      difficulty: "intermediate",
      beginner:
        "Imagine an assistant who, every morning, scans the day ahead and sends you the three things you absolutely need to know. Without being asked. That is exactly what Kami does — and in your own version, the same mechanism can send medication reminders, a daily team summary for work, or even a gentle 'how was your day?' to a child.",
      content: [
        "Cron 08:00 — personal morning briefing (today's tasks, calendar meetings, recap of yesterday)",
        "Cron 20:00 — evening summary (what got done during the day, what is still open, what to plan for tomorrow)",
        "Proactive scheduler — if an important message has not been answered within 30 minutes, Kami sends a gentle reminder",
        "Event-based triggers — when [Kaylee](/en/guide/kaylee) sends Kami an alert about an infrastructure issue, it automatically escalates to Elad",
        "Quiet hours (22:00 to 08:00) — Kami only sends genuinely urgent things, never routine summaries, during that window",
      ],
      tips: [
        "Awareness of the Israeli calendar is built into the code — on Shabbat, Memorial Day, Yom Kippur, and major holidays Kami automatically goes silent; well worth copying into any project that targets an Israeli audience",
        "You can add, edit, or disable any cron job at any moment — it is just one line in the Linux crontab file (crontab is the system's scheduling table)",
      ],
    },
    {
      id: "bridge",
      icon: Users,
      title: "Bridge to other agents",
      subtitle: "Kami talks to Claude Code and Kaylee via messages.jsonl",
      description:
        "Kami is not a lone agent — it is part of a network of agents that talk to each other. The bridge between them is implemented as a bridge file called messages.jsonl (a plain text file where each line is a single JSON message — a simple, resilient format that every programming language can read and write). This lets Kami forward requests to [Claude Code](/en/claude-code) on my machine, or to [Kaylee](/en/guide/kaylee) on the VPS, and route the replies back.",
      color: "from-cyan-600 to-blue-500",
      difficulty: "advanced",
      beginner:
        "Think of it as a private WhatsApp group just for the agents. You tell Kami 'check whether the server is up', it forwards the request to [Kaylee](/en/guide/kaylee) (the infrastructure agent in charge of every server), Kaylee runs the check and replies, and Kami brings the answer back to you on WhatsApp — all without you needing to know which agent does what behind the scenes.",
      content: [
        "The bridge itself is a JSON Lines file at ~/.claude/kami-bridge/messages.jsonl — a plain format with one message per line",
        "Every message carries these fields: {ts (timestamp), from (sender), to (recipient), content (payload), status (pending/handled), type (request/response)}",
        "Kami polls the file roughly every 10 seconds — spotting new messages addressed to it and processing them",
        "Kami can send messages to two recipients: claude-code (that is me on my machine) or kylie (that is [Kaylee](/en/guide/kaylee))",
        "[Claude Code](/en/claude-code) running on my Windows box reads the same file and responds whenever it sees messages directed to it",
        "[Kaylee](/en/guide/kaylee) on the VPS does not use the file — it listens on a dedicated HTTP endpoint (a network address that accepts incoming requests)",
      ],
      tips: [
        "If you want [Claude Code](/en/claude-code) to run a coding task while you are mid-conversation on WhatsApp — just tell Kami 'ask Claude to check X', and it will forward the request and bring the result back to you",
      ],
      codeExample: {
        label: "A bridge message",
        code: '{"ts":"2026-04-20T21:00:00Z","from":"elad","to":"claude-code","type":"request","content":"Check the project build","status":"pending"}',
      },
    },
    {
      id: "advanced",
      icon: Shield,
      title: "Advanced tips and automation",
      subtitle: "Lessons learned after six months of daily use",
      description:
        "These are the small things I (Elad) have learned after six months of using Kami every single day — the details that separate a generic bot from a personal agent that genuinely works for you. Each of them either fixed a bug for me or unlocked a meaningful capability, and they are all worth the time it takes to understand them.",
      color: "from-slate-600 to-zinc-500",
      difficulty: "advanced",
      content: [
        "WhatsApp Business vs Personal — Kami works perfectly with a regular personal number; Green API does not require a business profile or Meta verification",
        "Rate limits — the Green API free tier caps at 1,000 messages per month; the Pro plan starts at $39/month with no cap, which is cost-effective for heavy use",
        "Multi-user — you can add additional users in code and offer a personal agent to every family member, each with their own system prompt (dad gets one, mom another, the kids a third)",
        "Backup — messages.jsonl grows quickly; set up a weekly rotation that uploads to AWS S3 or Hetzner Object Storage (cheap archival storage for files)",
        "Monitoring — a tool called Uptime Kuma pings Kami's health endpoint (a URL that returns 'I'm alive') and fires an alert the moment the service goes down",
        "A/B testing for system prompts — duplicate system-prompt.ts into several variants and switch between them with an environment variable (ENV var — external configuration the program reads at startup), to see which personality resonates best",
      ],
      tips: [
        "The pattern that has paid off the most: 'mirror mode' — if you sent a voice note, Kami replies in voice; if you sent text, Kami replies in text. It creates a feeling of natural, frictionless communication",
        "It is worth adding a /status command in WhatsApp — it returns a compact system status (uptime, message count, memory usage) without consuming any LLM tokens, so it costs nothing",
      ],
    },
  ],
  resources: [
    {
      title: "GitHub — elad-personal-agent",
      description: "Kami's full source code — TypeScript + Bun + Claude + Whisper + Gemini TTS",
      href: "https://github.com/eladjak/elad-personal-agent",
      icon: Github,
    },
    {
      title: "Green API",
      description: "The official WhatsApp gateway — 1,000 free messages included",
      href: "https://green-api.com",
      icon: ExternalLink,
    },
    {
      title: "Qdrant Cloud",
      description: "Vector database that powers semantic memory",
      href: "https://qdrant.tech",
      icon: ExternalLink,
    },
    {
      title: "OpenAI Whisper API",
      description: "Accurate Hebrew voice transcription",
      href: "https://platform.openai.com/docs/guides/speech-to-text",
      icon: ExternalLink,
    },
    {
      title: "Gemini TTS",
      description: "Free Hebrew voices — Charon, Achernar, and 28 more",
      href: "https://ai.google.dev",
      icon: ExternalLink,
    },
    {
      title: "The full Claude Code guide",
      description: "The foundation behind the entire stack — how to use Claude Code",
      href: "/en/claude-code",
      icon: BookOpen,
    },
  ],
  ctaTitle: "Ready to build your own Kami?",
  ctaSub:
    "The code is open source, the APIs are cheap or free, and the time from zero to your first voice conversation is about 15 minutes.",
  primaryCta: {
    label: "Build your own Kami",
    href: "https://github.com/eladjak/elad-personal-agent",
    icon: Github,
  },
  secondaryCta: {
    label: "Message me on WhatsApp",
    href: "https://wa.me/972525427474",
    icon: Phone,
  },
  authorBio:
    "Kami is an AI agent I run in production and keep evolving. It started as a simple chatbot and has grown into a system that replies in voice, retains long-term context, and proactively surfaces reminders based on your habits. This guide is written so that you can understand the architecture, install your own version, and tailor the agent's personality to your needs — personal, family, or business.",
};
